### ISSUE TITLE
last_update vs last_build

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#32] opened 2023-09-11 07:03 UTC
Currently, the `timestamp` added to the corresponding version in `update.json` as well as the `last_update` in `track.json` take the timestamp of the modules ZIP file – which usually is the time the ZIP was built (or attached at the place `update_to`'s `update.json` points to). There's no way to tell what time this version reached the Magisk repo – `last_update` is rather `last_build`.

Would you consider an `added` field for the corresponding version entries in `update.json` to point out the date this specific version was added to the repo? Not sure how that should be reflected in `track.json`, as there a `last_update` is already present (maybe something like `last_update_repo` or `last_repo_update`).

Thanks for considering!

**Comment by SanmerDev** [comment] 2023-09-11 10:25
> There's no way to tell what time this version reached the Magisk repo – `last_update` is rather `last_build`.

I don't think users will be interested in this value 🤔.

**Comment by IzzySoft** [comment] 2023-09-11 10:44
I don't think it being *essential* – but the question sometimes arises how long a repo needs to update. Or like "what updates arrived at this repo yesterday?" is hard to answer when a dev only now provides a module compiled a week ago. An `added` at the version level would suffice for that I guess (as long as it ends up in the index, and not just in `update.json`), like `added` on module level indicates the time this module was added to the repo (not what time the first version ever added was built) – though having it available at module level would make things easier.

Speaking of that: with 2.0 it seems the order of entries in `versions` reverted. While before the newest version was first, it is now last. Will it stay that way? Or should I better take care to sort versions before picking what *should* be the newest?

**Comment by SanmerDev** [comment] 2023-09-11 11:22
> what updates arrived at this repo yesterday?

for this, I have added `cli.py sync --diff`

> While before the newest version was first, it is now last.

https://github.com/ya0211/magisk-modules-repo-util/blob/2f0d0f184acb8dc19add7f22f76a660b2275f3b5/sync/model/UpdateJson.py#L29

**Comment by IzzySoft** [comment] 2023-09-11 12:48
> for this, I have added `cli.py sync --diff`

Thanks, but what exactly does this do? Does it include diffs of the changelogs with the index? Does it tell at what time a version was added to the repo (and if so, where does it get that information from, if it's not stored somewhere)? I saw that new option in the commits, but found no explanation for it so far. And not all modules even have a changelog.

> While before the newest version was first, it is now last.

I expected that it's done in the code of course. My question was rather if the current ordering is now permanent – or if it might change again with a future version of repo-util :wink:

**Comment by SanmerDev** [comment] 2023-09-11 13:29
> if it might change again with a future version of repo-util

If there are no other significant changes, the order will not change.

**Closed as not planned by SanmerDev** 2023-09-11 13:29 UTC

**Comment by IzzySoft** [comment] 2023-09-11 13:46
Then I hope I'll notice in-time should the unlikely happen :wink:

Remains the original question of an `added` entry for versions. For all existing entries not having it, it could be populated with the timestamp of the corresponding changelog (if any), falling back to the timestamp of the `update.json` for the newest one or the `last_update` if it's older (or not the latest version). Would you consider that?

**Comment by SanmerDev** [comment] 2023-09-11 14:11
I think it would be best to keep the current solution unchanged  https://github.com/ya0211/magisk-modules-repo-util/issues/6#issuecomment-1494635130.

**Comment by IzzySoft** [comment] 2023-09-11 14:23
True – and I didn't suggest to change that, but rather to introduce an `added` field to the corresponding version in `update.json` (which you touch anyway when an update takes place), filled with `now()` i.e. the time the version was added to the repo. Like this:

```json
    {
      "timestamp": 1683098152.0,
      "added": 1692914400.0,
      "version": "2.8.0",
      "versionCode": 242,
      "zipUrl": "https://apt.izzysoft.de/magisk/modules/AOSPMods/2.8.0_242.zip",
      "changelog": "https://apt.izzysoft.de/magisk/modules/AOSPMods/2.8.0_242.md"
    }
```

if this update from August 22nd (`timestamp`) would have been added to the repo on August 25th (`added`).

**Comment by SanmerDev** [comment] 2023-09-11 15:13
I think having a timestamp is sufficient. As for when it was added, I think it doesn't hold much significance. 🤔

**Comment by SanmerDev** [comment] 2023-09-11 15:18
I even think that module-level `added` doesn't have much usefulness 😶‍🌫️.

**Comment by IzzySoft** [comment] 2023-09-11 15:40
Well, I think differently – but I accept your decision and not press further. It's something I'd feel nice to have; but then I'll simply have to remove one of the two filters here. Just undecided now which one to keep: "last build" would be what the current timestamp reflects – but having that without "last update" looks a bit weird. But the other way around, "last update" with the [WebIF for Magisk](https://apt.izzysoft.de/magisk) would have a different meaning than the one for the identically looking [F-Droid WebIf](https://apt.izzysoft.de/fdroid), which is also a little weird :thinking:

**Comment by SanmerDev** [comment] 2023-09-11 15:54
I believe focusing on `last update` (or calling it `last build`) would suffice. Ideally, we would want it to update in real-time (but it's not possible due to resource constraints), so we can simply pay attention to `last update` (since `last added` and `last build` would have the same value as well).

Even if we cannot update in real-time, I still believe that focusing on `last update` is sufficient 😶‍🌫️.

**Comment by IzzySoft** [comment] 2023-09-11 16:08
OK, then that it will be. As everything seems to work really fine now, I'll integrate it with my Cron jobs soon anyway, so the difference should rarely be more than a day (with the exception of some older ZIP being provided by the developer only days later).

One last question (I can open a separate issue for that if you wish): it would make filtering log output easier if each entry would be kept on a single line. Example here:

```
[2023/09/11 16:55:49] Pull WARNING: _get_changelog_common: [jdtoolbox] -> 'Add support for using bootable kernel flashers as input to kernel installer
Add kernel+dtb install menu' unsupported type
```

It seems the dev doesn't want to fix that – but filtering it out with `grep -v` is tricky for such cases. So each Cron run would produce a mail, even if there's no other message. And you know how it is: the one day you don't even look at that mail expecting it to just be just the usual thing, something else is reported along that would have required your attention :wink:

**Comment by SanmerDev** [comment] 2023-09-11 16:17
This issue is likely caused by the `\n` in the changelog. I will find a way to handle this type of changelog.

**Comment by IzzySoft** [comment] 2023-09-11 16:29
:star_struck: Thanks! If you need an example for testing: [jdtoolbox is here](https://github.com/JoshuaDoes/jdtoolbox).

**Comment by SanmerDev** [comment] 2023-09-11 17:02
> This issue is likely caused by the `\n` in the changelog. I will find a way to handle this type of changelog.

Fixed in https://github.com/ya0211/magisk-modules-repo-util/commit/89edbd7a84b8a8d8d990f542ccd96aed7270b599 and https://github.com/ya0211/magisk-modules-repo-util/commit/c6f5c9998a71472103b2fd552c1b63cb76527606

**Comment by IzzySoft** [comment] 2023-09-11 21:59
```
[2023/09/11 23:55:58] Config WARNING: _check_values: 'name' is undefined
Traceback (most recent call last):
  File "/sanitized/magisk/util/cli.py", line 26, in <module>
    sys.exit(Main.exec())
  File "/sanitized/magisk/util/sync/cli/Main.py", line 55, in exec
    code = cls._check_args()
  File "/sanitized/magisk/util/sync/cli/Main.py", line 75, in _check_args
    return cls.sync()
  File "/sanitized/magisk/util/sync/cli/Main.py", line 247, in sync
    config = Config(root_folder)
  File "/sanitized/magisk/util/sync/core/Config.py", line 21, in __init__
    self._check_values()
  File "/sanitized/magisk/util/sync/core/Config.py", line 36, in _check_values
    raise ConfigError("'base_url' is undefined")
sync.error.ConfigError.ConfigError: 'base_url' is undefined
```

I just replaced `util`. Replacing it again by the original version, no crash. Config was not touched.

**Comment by SanmerDev** [comment] 2023-09-12 01:10
@IzzySoft To use the HEAD `util`, first run `cli.py config --migrate` and `cli.py track --migrate` for migration.

**Comment by IzzySoft** [comment] 2023-09-12 04:24
Ah, I wasn't aware of that, thanks for the hint!! Now it looks different:

```
[2023/09/12 05:57:31] Pull ERROR: from_git: [hifi-maximizer-mod] -> FileNotFoundError(2 No such file or directory)
'/web/ftp/repo/magisk/util/cli.py sync' returned '1', aborting.
```

(that was called from my wrapper script). So it looks like return codes have changed as well: running `cli.py sync` manually, it runs through fine – and funnily returns `0`. Next run, it returns `1` again – but from the log output I cannot tell why (doesn't look different). Then again `0` (from the wrapper script, too). This never happened before – and makes it difficult running it automatically. Also, on every run now I get this:

```
Pull ERROR: from_git: [audio-jitter-silencer] -> HTTPError(clone failed: https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer.git)
Pull ERROR: from_git: [hifi-maximizer-mod] -> HTTPError(clone failed: https://github.com/yzyhk904/hifi-maximizer-mod.git)
```

The repos are there, and running `git clone https://github.com/yzyhk904/hifi-maximizer-mod.git` works fine (also for the other repo). Funnily, so does `util/cli.py sync -i hifi-maximizer-mod` (same for the other module) – and after having done this explicitly for the two modules, the error is gone with the next full run, strange… And now it's a different module:

```
Pull ERROR: from_git: [drc-remover] -> FileNotFoundError(2 No such file or directory)
```

Again, no idea why: `"update_to": "https://github.com/Magisk-Modules-Alt-Repo/drc-remover.git"`, and the repo exists. `util/cli.py sync -i drc-remover` also fails, but with a different error:

```
Pull ERROR: from_git: [drc-remover] -> HTTPError(clone failed: https://github.com/Magisk-Modules-Alt-Repo/drc-remover.git)
```

Succeeds on a subsequent run. So TL;DR: current `HEAD` seems to be quite unpredictable. Guess I better wait before updating to that?

**Comment by SanmerDev** [comment] 2023-09-12 04:48
I'm not sure about the issue regarding `FileNotFoundError` and `HTTPError`. It could be due to differences in Python versions (possibly caused by multi-threading). Currently, I have only tested the compatibility of `util` on versions 3.11 and 3.10.

Even with the latest version (v2.2.0), testing is not possible on Python 3.9 https://github.com/ya0211/magisk-modules-alt-repo/commit/054eeb70070acd4f28c9ac6b08b5d9e3563de1bc.

**Comment by IzzySoft** [comment] 2023-09-14 18:37
Sorry for the late reply, I was AFK for a conference…

> It could be due to differences in Python versions (possibly caused by multi-threading).

Multi-threading was already available with the last version I've used and ran fine. This issue only started after I updated to HEAD due to your above mentioned fixes.

> testing is not possible on Python 3.9

I'm still on Python 3.8.2 here (LTS version of Linux Mint), and upgrading to a newer Python release is only possible with upgrading the entire machine, which is currently not possible here. So my choices are going back to the last release (which did not have these issues), or live with the issue. If you let me know how I could help finding the cause of the two mentioned errors, I can look into that.

Might be this was just a temporary hick-up e.g. on Github's end (I just ran `sync` now and all looked fine), so if you prefer I can simply watch it for a while, leaving the updates as manual task for a little longer.

**Comment by IzzySoft** [comment] 2023-09-15 16:09
@ya0211 shall we split this off to a separate issue? It still happens every other run. Right now, 3 subsequent runs:

```
[2023/09/15 17:56:17] Pull ERROR: from_git: [data_isolation_support] -> FileNotFoundError(2 No such file or directory)
[2023/09/15 17:57:26] Pull ERROR: from_git: [data_isolation_support] -> HTTPError(clone failed: https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support.git)
[2023/09/15 17:57:37] Pull INFO: _check_version_code: [data_isolation_support] -> already the latest version
```

The thing in common: it seems only to affect modules which are updated via `git pull` (i.e. with an `update_to` ending with `.git`). I have only 7 of those (out of 82), and so far it was always one of them (as my previous comments show). As you suspect multi-threading here: maybe limiting parallel cloning? I will meanwhile check if I can change a few of them to other methods (though I doubt it; I had done that before if it would be possible, but the repos might have changed since).

**Comment by IzzySoft** [comment] 2023-11-27 00:10
BTW, just to conclude this: Haven't seen that `git pull` issue for a while now, though I didn't enforce single-thread. Must have been an issue at Github then.
